org: dshilman
app: snowflake-python-api
service: 'snowflake-python-api'

custom:
  wsgi:
    app: app.app
    packRequirements: false
  
provider:
  name: aws
  runtime: python3.9
  region: us-east-1

functions:
  api:
    handler: wsgi_handler.handler
    environment:
      SNOWFLAKE_ACCOUNT: 'iob03793.us-east-1'
      SNOWFLAKE_USER: 'DATA_APPS_DEMO'
      SNOWFLAKE_DATABASE: 'DATA_APPS_DEMO'
      SNOWFLAKE_SCHEMA: 'DEMO'
      SNOWFLAKE_WAREHOUSE: 'DATA_APPS_DEMO'
      SNOWFLAKE_PRIVATE_KEY: ${ssm:/597782288487.DATA_APPS_DEMO}
    timeout: 15
    events:
      - http:
          path: /trips/monthly
          method: GET
      - http:
          path: /trips/day_of_week
          method: GET
      - http:
          path: /trips/temperature
          method: GET
      - http:
          path: /sqlapi/trips/monthly
          method: GET
      - http:
          path: /sqlapi/trips/day_of_week
          method: GET
      - http:
          path: /sqlapi/trips/temperature
          method: GET 

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  patterns:
    - '!__pycache__/**'
    - '!_node_modules/**'
    - '!.venv/**'

